general.import = [
  "catpuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/local/bin/zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "Buttonless"
opacity = 0.98

[cursor]
style.blinking = "On"

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 15.0
